module

public import CoveringSystem2
public import Mathlib.Data.Int.ModEq
public import Mathlib.RingTheory.Ideal.Norm.AbsNorm
public import Mathlib.Algebra.GCDMonoid.Nat
public import Mathlib.Tactic


@[expose] public section

/-!
# Ideal-coset to integer-congruence statement adapter for Erdős #2

Connects the `StrictCoveringSystem ℤ` formulation in `FormalConjectures`
(`CoveringSystem2`) to indexed integer congruences `Int.ModEq`, proving that
`UniformNumericalBound` refutes `ArbitrarilyLargeIdealCoverings` and yields the
literal `False ↔ ...` Formal Conjectures statement.
-/

open scoped Pointwise

namespace Erdos2Statement

/-- Equality of principal ideals generated by naturals entails equality of the
natural generators, including zero. No signed-generator ambiguity remains. -/
theorem natGenerator_injective :
    Function.Injective (fun m : ℕ => Ideal.span {(m : ℤ)}) := by
  intro m n h
  have hAbs := Int.associated_iff_natAbs.mp
    (Ideal.span_singleton_eq_span_singleton.mp h)
  simpa using hAbs

/-- A principal ideal coset is the signed congruence class with its given
generator; this equivalence is valid even for a zero or negative generator. -/
theorem mem_principal_coset_iff_modEq (r z m : ℤ) :
    z ∈ ({r} : Set ℤ) + (Ideal.span {m} : Set ℤ) ↔
      Int.ModEq m r z := by
  rw [Set.mem_add, Int.modEq_iff_dvd]
  constructor
  · rintro ⟨x, hx, y, hy, hxy⟩
    have hx' : x = r := by simpa using hx
    subst x
    have hy' : m ∣ y := Ideal.mem_span_singleton.mp hy
    have hz : z - r = y := by omega
    rwa [hz]
  · intro h
    exact ⟨r, by simp, z - r, Ideal.mem_span_singleton.mpr h, by omega⟩

/-- Distinct ideals force any assigned natural generators to be distinct. -/
theorem generators_injective (c : StrictCoveringSystem ℤ)
    (m : c.ι → ℕ)
    (hm : ∀ i, c.moduli i = Ideal.span {(m i : ℤ)}) :
    Function.Injective m := by
  intro i j hij
  apply c.injective_moduli
  rw [hm i, hm j, hij]

/-- The ideal-coset coverage equation is equivalent to coverage of all signed
integers by the assigned numerical congruences. No positivity is needed here. -/
theorem unionCovers_iff_modEq (c : CoveringSystem ℤ)
    (m : c.ι → ℕ)
    (hm : ∀ i, c.moduli i = Ideal.span {(m i : ℤ)}) :
    (⋃ i, ({c.residue i} : Set ℤ) + (c.moduli i : Set ℤ)) = Set.univ ↔
      ∀ z : ℤ, ∃ i, Int.ModEq (m i : ℤ) (c.residue i) z := by
  constructor
  · intro h z
    have hz : z ∈ ⋃ i, ({c.residue i} : Set ℤ) + (c.moduli i : Set ℤ) := by
      rw [h]
      exact Set.mem_univ z
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hz
    exact ⟨i, (mem_principal_coset_iff_modEq (c.residue i) z (m i)).mp
      (by simpa only [hm i] using hi)⟩
  · intro h
    apply Set.eq_univ_of_forall
    intro z
    obtain ⟨i, hi⟩ := h z
    apply Set.mem_iUnion.mpr
    exact ⟨i, by simpa only [hm i] using
      (mem_principal_coset_iff_modEq (c.residue i) z (m i)).mpr hi⟩

/-- The exact right-hand side of the current Formal Conjectures #2 statement. -/
def ArbitrarilyLargeIdealCoverings : Prop :=
  ∀ B : ℕ, ∃ c : StrictCoveringSystem ℤ, ∀ i, ∃ m : ℕ,
    c.moduli i = Ideal.span {(m : ℤ)} ∧ B < m

/-- The numerical theorem the probability sieve must prove. The bound is
uniform in the finite index type, distinct positive moduli, and integer residues.
Modulus one is harmless: it already lies below any useful universal bound. -/
def UniformNumericalBound : Prop :=
  ∃ B : ℕ, ∀ {ι : Type} [Fintype ι] (m : ι → ℕ) (r : ι → ℤ),
    Function.Injective m → (∀ i, 0 < m i) →
    (∀ z : ℤ, ∃ i, Int.ModEq (m i : ℤ) (r i) z) →
    ∃ i, m i ≤ B

/-- Conditional statement adapter: supplied principal generators avoid any
extra principal-ideal theorem. This does not discharge its numerical hypothesis. -/
theorem not_arbitrarilyLarge_of_uniformNumericalBound
    (hbound : UniformNumericalBound) : ¬ArbitrarilyLargeIdealCoverings := by
  classical
  obtain ⟨B, hB⟩ := hbound
  intro hlarge
  obtain ⟨c, hc⟩ := hlarge B
  haveI : Fintype c.ι := c.toCoveringSystem.fintypeIndex
  let m : c.ι → ℕ := fun i => Classical.choose (hc i)
  have hm : ∀ i, c.moduli i = Ideal.span {(m i : ℤ)} :=
    fun i => (Classical.choose_spec (hc i)).1
  have hgt : ∀ i, B < m i := fun i => (Classical.choose_spec (hc i)).2
  have hinj : Function.Injective m := generators_injective c m hm
  have hpos : ∀ i, 0 < m i := fun i => lt_of_le_of_lt (Nat.zero_le B) (hgt i)
  have hcover : ∀ z : ℤ, ∃ i, Int.ModEq (m i : ℤ) (c.residue i) z :=
    (unionCovers_iff_modEq c.toCoveringSystem m hm).mp c.unionCovers
  obtain ⟨i, hi⟩ := hB m c.residue hinj hpos hcover
  exact (Nat.not_lt_of_ge hi) (hgt i)

/-- The catalog's `answer(False)` is False. This is its literal original
statement, conditional only on the uniform numerical theorem above. -/
theorem formalConjectures_statement_of_uniformNumericalBound
    (hbound : UniformNumericalBound) :
    False ↔ ∀ B : ℕ, ∃ c : StrictCoveringSystem ℤ, ∀ i, ∃ m : ℕ,
      c.moduli i = Ideal.span {(m : ℤ)} ∧ B < m := by
  constructor
  · intro h
    exact h.elim
  · exact not_arbitrarilyLarge_of_uniformNumericalBound hbound

end Erdos2Statement
