import Mathlib.Algebra.Polynomial.BigOperators
import Mathlib.Algebra.Polynomial.Derivative
import Mathlib.Analysis.Complex.Basic
import Mathlib.RingTheory.PowerSeries.Basic
import Mathlib.Tactic.GCongr
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Positivity

/-!
# The algebraic projected-Newton bridge for Erdős problem 973

All point configurations in this file are finite; points need not be distinct,
nonzero, or exterior.  No analytic lower bound is assumed or proved here.
-/

noncomputable section

open scoped BigOperators
open Polynomial

namespace Erdos973

variable {ι : Type*}

/-- The reciprocal-root polynomial generated by a finite point configuration. -/
def rootPolynomial (s : Finset ι) (z : ι → ℂ) : ℂ[X] :=
  ∏ i ∈ s, (1 - C (z i) * X)

/-- A power sum with the same multiplicities and index set as `rootPolynomial`. -/
def powerSum (s : Finset ι) (z : ι → ℂ) (k : ℕ) : ℂ :=
  ∑ i ∈ s, z i ^ k

/-- The differential residual with its constant coefficient removed. -/
def residual (P : ℂ[X]) : ℂ[X] :=
  P.derivative - C (P.derivative.eval 0) * P

private def geometricSeries (z : ℂ) : PowerSeries ℂ :=
  PowerSeries.mk fun k => z ^ k

private theorem factor_mul_geometricSeries (z : ℂ) :
    (1 - PowerSeries.C z * PowerSeries.X) * geometricSeries z = 1 := by
  ext k
  cases k with
  | zero => simp [geometricSeries, sub_mul, mul_assoc]
  | succ k => simp [geometricSeries, sub_mul, mul_assoc, pow_succ']

@[simp] theorem rootPolynomial_eval_zero (s : Finset ι) (z : ι → ℂ) :
    (rootPolynomial s z).eval 0 = 1 := by
  simp [rootPolynomial, Polynomial.eval_prod]

@[simp] theorem rootPolynomial_coeff_zero (s : Finset ι) (z : ι → ℂ) :
    (rootPolynomial s z).coeff 0 = 1 := by
  simpa only [Polynomial.coeff_zero_eq_eval_zero] using rootPolynomial_eval_zero s z

theorem rootPolynomial_natDegree_le (s : Finset ι) (z : ι → ℂ) :
    (rootPolynomial s z).natDegree ≤ s.card := by
  calc
    (rootPolynomial s z).natDegree ≤
        ∑ i ∈ s, (1 - C (z i) * X : ℂ[X]).natDegree :=
      Polynomial.natDegree_prod_le _ _
    _ ≤ ∑ _i ∈ s, 1 := by
      apply Finset.sum_le_sum
      intro i hi
      exact (Polynomial.natDegree_sub_le _ _).trans (max_le (by simp)
        ((Polynomial.natDegree_C_mul_le _ _).trans (by simp)))
    _ = s.card := by simp

theorem differential_residual_natDegree_le (G : ℂ[X]) (mu : ℂ) :
    (G.derivative - C mu * G).natDegree ≤ G.natDegree := by
  exact (Polynomial.natDegree_sub_le _ _).trans (max_le
    ((Polynomial.natDegree_derivative_le _).trans (Nat.sub_le _ _))
    (Polynomial.natDegree_C_mul_le _ _))

theorem residual_natDegree_le (P : ℂ[X]) :
    (residual P).natDegree ≤ P.natDegree := by
  exact differential_residual_natDegree_le P (P.derivative.eval 0)

@[simp] theorem residual_coeff_zero (P : ℂ[X]) (hP : P.coeff 0 = 1) :
    (residual P).coeff 0 = 0 := by
  simp [residual, ← Polynomial.coeff_zero_eq_eval_zero, hP]

private theorem rootPolynomial_derivative_series (s : Finset ι) (z : ι → ℂ) :
    ((rootPolynomial s z).derivative : PowerSeries ℂ) =
      -(rootPolynomial s z : PowerSeries ℂ) *
        ∑ i ∈ s, PowerSeries.C (z i) * geometricSeries (z i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [rootPolynomial]
  | @insert a s ha ih =>
    have hP : rootPolynomial (insert a s) z =
        (1 - C (z a) * X) * rootPolynomial s z := by
      simp [rootPolynomial, ha]
    rw [hP, Polynomial.derivative_mul]
    simp only [Polynomial.derivative_sub, Polynomial.derivative_one,
      Polynomial.derivative_C_mul, Polynomial.derivative_X, mul_one, zero_sub,
      Polynomial.coe_add, Polynomial.coe_mul, Polynomial.coe_neg,
      Polynomial.coe_C, Polynomial.coe_sub, Polynomial.coe_one,
      Polynomial.coe_X, ih, Finset.sum_insert ha]
    have hg := factor_mul_geometricSeries (z a)
    linear_combination (rootPolynomial s z : PowerSeries ℂ) * PowerSeries.C (z a) * hg

/-- Newton's coefficient identity, including all degrees above the polynomial degree. -/
theorem rootPolynomial_derivative_coeff (s : Finset ι) (z : ι → ℂ) (m : ℕ) :
    (rootPolynomial s z).derivative.coeff m =
      -∑ j ∈ Finset.range (m + 1),
        (rootPolynomial s z).coeff j * powerSum s z (m + 1 - j) := by
  have h := congrArg (PowerSeries.coeff m) (rootPolynomial_derivative_series s z)
  simp only [Polynomial.coeff_coe] at h
  rw [PowerSeries.coeff_mul] at h
  simp only [map_neg, Polynomial.coeff_coe, map_sum,
    PowerSeries.coeff_C_mul, geometricSeries, PowerSeries.coeff_mk, neg_mul] at h
  rw [Finset.sum_neg_distrib] at h
  rw [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk] at h
  convert h using 1
  congr 1
  apply Finset.sum_congr rfl
  intro j hj
  have hjm : j ≤ m := Nat.le_of_lt_succ (Finset.mem_range.mp hj)
  simp only [powerSum]
  rw [show m + 1 - j = (m - j) + 1 by omega]
  simp only [pow_succ']

@[simp] theorem rootPolynomial_derivative_eval_zero (s : Finset ι) (z : ι → ℂ) :
    (rootPolynomial s z).derivative.eval 0 = -powerSum s z 1 := by
  rw [← Polynomial.coeff_zero_eq_eval_zero, rootPolynomial_derivative_coeff]
  simp

/-- The projected identity excludes exactly the first power sum. -/
theorem residual_rootPolynomial_coeff (s : Finset ι) (z : ι → ℂ) (m : ℕ) :
    (residual (rootPolynomial s z)).coeff m =
      -∑ j ∈ Finset.range m,
        (rootPolynomial s z).coeff j * powerSum s z (m + 1 - j) := by
  rw [residual, Polynomial.coeff_sub, Polynomial.coeff_C_mul,
    rootPolynomial_derivative_eval_zero, rootPolynomial_derivative_coeff,
    Finset.sum_range_succ]
  rw [show m + 1 - m = 1 by omega]
  ring

/-- Solving the projected identity for its highest power sum. -/
theorem powerSum_eq_residual_recurrence (s : Finset ι) (z : ι → ℂ) (m : ℕ) :
    powerSum s z (m + 2) =
      -(residual (rootPolynomial s z)).coeff (m + 1) -
        ∑ j ∈ Finset.range m,
          (rootPolynomial s z).coeff (j + 1) * powerSum s z (m + 1 - j) := by
  have h := residual_rootPolynomial_coeff s z (m + 1)
  rw [Finset.sum_range_succ'] at h
  simp only [rootPolynomial_coeff_zero, Nat.sub_zero, one_mul] at h
  have hs : (∑ j ∈ Finset.range m,
      (rootPolynomial s z).coeff (j + 1) * powerSum s z (m + 1 + 1 - (j + 1))) =
      ∑ j ∈ Finset.range m,
        (rootPolynomial s z).coeff (j + 1) * powerSum s z (m + 1 - j) := by
    apply Finset.sum_congr rfl
    intro j hj
    rw [show m + 1 + 1 - (j + 1) = m + 1 - j by omega]
  rw [hs] at h
  linear_combination h

/-- A coefficientwise bound using only the requested powers `2,...,n+1`. -/
theorem residual_rootPolynomial_coeff_norm_le (s : Finset ι) (z : ι → ℂ)
    (n m : ℕ) (M : ℝ)
    (hM : ∀ k ∈ Finset.Icc 2 (n + 1), ‖powerSum s z k‖ ≤ M)
    (hm : m ≤ n) :
    ‖(residual (rootPolynomial s z)).coeff m‖ ≤
      M * ∑ j ∈ Finset.range m, ‖(rootPolynomial s z).coeff j‖ := by
  rw [residual_rootPolynomial_coeff, norm_neg]
  calc
    ‖∑ j ∈ Finset.range m,
        (rootPolynomial s z).coeff j * powerSum s z (m + 1 - j)‖ ≤
        ∑ j ∈ Finset.range m,
          ‖(rootPolynomial s z).coeff j * powerSum s z (m + 1 - j)‖ :=
      norm_sum_le _ _
    _ ≤ ∑ j ∈ Finset.range m, M * ‖(rootPolynomial s z).coeff j‖ := by
      apply Finset.sum_le_sum
      intro j hj
      have hjm := Finset.mem_range.mp hj
      rw [norm_mul, mul_comm M]
      exact mul_le_mul_of_nonneg_left (hM _ (Finset.mem_Icc.mpr (by omega)))
        (norm_nonneg _)
    _ = _ := by rw [Finset.mul_sum]

/-- A common coefficient bound controls every residual coefficient. -/
theorem residual_rootPolynomial_coeff_norm_le_of_bound
    (s : Finset ι) (z : ι → ℂ) (n m : ℕ) (M A : ℝ)
    (hM0 : 0 ≤ M)
    (hM : ∀ k ∈ Finset.Icc 2 (n + 1), ‖powerSum s z k‖ ≤ M)
    (hA : ∀ j ≤ n, ‖(rootPolynomial s z).coeff j‖ ≤ A)
    (hm : m ≤ n) :
    ‖(residual (rootPolynomial s z)).coeff m‖ ≤ (n : ℝ) * M * A := by
  have hA0 : 0 ≤ A := (norm_nonneg _).trans (hA 0 (Nat.zero_le _))
  calc
    ‖(residual (rootPolynomial s z)).coeff m‖ ≤
        M * ∑ j ∈ Finset.range m, ‖(rootPolynomial s z).coeff j‖ :=
      residual_rootPolynomial_coeff_norm_le s z n m M hM hm
    _ ≤ M * ∑ _j ∈ Finset.range m, A := by
      apply mul_le_mul_of_nonneg_left _ hM0
      exact Finset.sum_le_sum fun j hj => hA j (by have := Finset.mem_range.mp hj; omega)
    _ = M * ((m : ℝ) * A) := by simp
    _ ≤ M * ((n : ℝ) * A) := by
      gcongr
    _ = _ := by ring

/-- The residual on the closed unit disk is controlled by the point power sums. -/
theorem residual_rootPolynomial_eval_norm_le
    (s : Finset ι) (z : ι → ℂ) (n : ℕ) (M A : ℝ)
    (hs : s.card ≤ n) (hM0 : 0 ≤ M)
    (hM : ∀ k ∈ Finset.Icc 2 (n + 1), ‖powerSum s z k‖ ≤ M)
    (hA : ∀ j ≤ n, ‖(rootPolynomial s z).coeff j‖ ≤ A)
    (w : ℂ) (hw : ‖w‖ ≤ 1) :
    ‖(residual (rootPolynomial s z)).eval w‖ ≤
      (n : ℝ) * (n + 1) * M * A := by
  have hd : (residual (rootPolynomial s z)).natDegree < n + 1 :=
    Nat.lt_succ_of_le ((residual_natDegree_le _).trans
      ((rootPolynomial_natDegree_le s z).trans hs))
  rw [Polynomial.eval_eq_sum_range' hd]
  calc
    ‖∑ m ∈ Finset.range (n + 1),
        (residual (rootPolynomial s z)).coeff m * w ^ m‖ ≤
        ∑ m ∈ Finset.range (n + 1),
          ‖(residual (rootPolynomial s z)).coeff m * w ^ m‖ := norm_sum_le _ _
    _ ≤ ∑ _m ∈ Finset.range (n + 1), (n : ℝ) * M * A := by
      apply Finset.sum_le_sum
      intro m hm
      calc
        ‖(residual (rootPolynomial s z)).coeff m * w ^ m‖ ≤
            ‖(residual (rootPolynomial s z)).coeff m‖ := by
          rw [norm_mul, norm_pow]
          exact mul_le_of_le_one_right (norm_nonneg _) (pow_le_one₀ (norm_nonneg _) hw)
        _ ≤ _ := residual_rootPolynomial_coeff_norm_le_of_bound
          s z n m M A hM0 hM hA (by have := Finset.mem_range.mp hm; omega)
    _ = _ := by simp; ring

/-- A maximal-coefficient argument bounds the omitted first power sum.
No Bernstein inequality, exterior condition, or analytic theorem is used. -/
theorem powerSum_one_norm_le
    (s : Finset ι) (z : ι → ℂ) (n : ℕ) (M : ℝ)
    (hs : s.card ≤ n) (hM0 : 0 ≤ M)
    (hM : ∀ k ∈ Finset.Icc 2 (n + 1), ‖powerSum s z k‖ ≤ M) :
    ‖powerSum s z 1‖ ≤ (n : ℝ) + n * M := by
  obtain ⟨k, hk, hmax⟩ :=
    (Finset.range (n + 1)).exists_max_image
      (fun j => ‖(rootPolynomial s z).coeff j‖) (by simp)
  have hkn : k ≤ n := by have := Finset.mem_range.mp hk; omega
  let A : ℝ := ‖(rootPolynomial s z).coeff k‖
  have hA : ∀ j ≤ n, ‖(rootPolynomial s z).coeff j‖ ≤ A := by
    intro j hj
    exact hmax j (Finset.mem_range.mpr (by omega))
  have hA1 : 1 ≤ A := by simpa using hA 0 (Nat.zero_le n)
  have hA0 : 0 < A := lt_of_lt_of_le zero_lt_one hA1
  have hd : ‖(rootPolynomial s z).derivative.coeff k‖ ≤ (n : ℝ) * A := by
    by_cases hkn' : k < n
    · rw [Polynomial.coeff_derivative, norm_mul, ← Nat.cast_add_one,
        Complex.norm_natCast, mul_comm (n : ℝ)]
      exact mul_le_mul (hA _ (by omega)) (by exact_mod_cast (show k + 1 ≤ n by omega))
        (by positivity) (by positivity)
    · have hzero : (rootPolynomial s z).coeff (k + 1) = 0 :=
        Polynomial.coeff_eq_zero_of_natDegree_lt
          (lt_of_le_of_lt ((rootPolynomial_natDegree_le s z).trans hs) (by omega))
      simp only [Polynomial.coeff_derivative, hzero, zero_mul, norm_zero]
      positivity
  have he := residual_rootPolynomial_coeff_norm_le_of_bound s z n k M A hM0 hM hA hkn
  have hmu :
      (rootPolynomial s z).derivative.eval 0 * (rootPolynomial s z).coeff k =
        (rootPolynomial s z).derivative.coeff k -
          (residual (rootPolynomial s z)).coeff k := by
    simp [residual]
  have hbound : ‖powerSum s z 1‖ * A ≤ ((n : ℝ) + n * M) * A := by
    calc
      ‖powerSum s z 1‖ * A =
          ‖(rootPolynomial s z).derivative.eval 0 * (rootPolynomial s z).coeff k‖ := by
        simp [A]
      _ ≤ ‖(rootPolynomial s z).derivative.coeff k‖ +
            ‖(residual (rootPolynomial s z)).coeff k‖ := by rw [hmu]; exact norm_sub_le _ _
      _ ≤ (n : ℝ) * A + n * M * A := add_le_add hd he
      _ = _ := by ring
  nlinarith

end Erdos973
